### PR TITLE
Initial commit to Hw1

### PR DESCRIPTION
**Pull request by prakharchandna**
This is a PR for code `D02_ex00.py`

### CODE REVIEW

**Comment by prakharchandna** [comment]
@ProximaDas please review my code

**Comment by ProximaDas** [comment]
**HW01_ch01_ex02_03**

- Missing print statements

- Missing notes/comments, or step by step parameters for the code. Such a code will be difficult for a second reader to check quickly, and understand what's going on without reading & mentally executing the code

**HW01_ch02_ex00_01**

- Missing quotes in print(x=5) which is resulting into the error

**HW01_ch02_ex00_02**
Would be great if the code was written in a way that I could run & check the output as well. Otherwise, looks good

**HW02_ch03_ex01**
Looks good

**HW02_ch03_ex02**
Looks good

**HW02_ch03_ex03**
Looks good.
One good thing would be to have some separation b/w the two grids, with some text or spacing to make it more "readable"

**HW02_ch05_ex00**
Looks good

**HW02_ch05_ex02**

- This is missing edge case considerations for negative integers, as well as zeros.

- Check for n>2 is also missing

- Exception handling for non-numeric or decimal entries is not present

**HW02_ch05_ex03**
Looks good

**Comment by ProximaDas** [comment]
**HW02_ch07_ex02**
- Fun fact: 0^0 is a very ambiguous parameter. So in mathematical eval functions, adding for validation for this is also a good practice. Since the x^y function is not continuous at origin, some argue that Python results into an incorrect value of 1 for this.

- Exception handling is missing

**HW02_ch08_ex00**
Looks good

**HW04_ch08_ex04**
Nicely done

**HW02_ch08_ex05**
Great work
One thing to ponder over - "convertedStr = convertedStr + rotate_letter(letter, rotIndex)"
This statement makes the operation very expensive from program memory perspective. Can you think why?
Hint - Strings in python are immutable

**Comment by ProximaDas** [comment]
**HW02_ex06**
Good work.
One advice: Adding try/except to code, and checking for invalid inputs, and error use-cases is a must for any program. Do try to make this a habit

**HW02_string1.py**
Good work

**HW02_string2**
Good work

**Pull request merged**
